name: Feature Request
description: Suggest an idea for this app
title: "[Feature]: "
labels: ["Type: Enhancement"]
body:
- type: textarea
  attributes:
    label: Why?
    description: What sort of problem would this feature fix?
    placeholder: I expect [...] when I do [...]
  validations:
    required: true

- type: textarea
  attributes:
    label: What?
    description: Clear description of the feature you want to see.
    placeholder: Add functionality to [...]
  validations:
    required: true
