on:
  workflow_dispatch

name: Manual Release
jobs:
  manual_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download Artifact from latest workflow run
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
      - run: ls
